### ISSUE TITLE
It's a test issue.

### ISSUE THREAD

**Issue by jerikchan** [YoubetDao/youbet-task#44]
Start

**Comment by jerikchan** [comment]
openbuild意图是对他们的有帮助，Bounty，具体的不清楚。先介绍下。

openbuild：camp 这边社区的小伙伴对github统计很麻烦。

youbet：开源软件作者贡献没有被嘉奖。用这套模式管理需求任务、发放奖励。issue驱动管理任务，每个task是一个issue，assign、claim、points、points上链、pr review、pr close、链上数据发生变化、rewards有人发放、打赏。

openbuild：不太自动化。webhook 监听 pr 更新、修改 readme。开发者不希望污染他的PR。开发就两个人，没有人力开发。

微扰：能否合作

openbuild：希望用你们的系统替换现在的。PR和webhook驱动流程更新，和之前的需求对起来，很像。有一些定制需求、作者不希望污染项目。作者可以在前端入口提供一个手动的更新。完成项目可以开放资源。对项目的支持，PMC。PMC是openbuild的一个核心组织，可以快速聚拢一批开发者，是一个兴趣组，贡献者。融资得和xxx聊，不清楚。

openbuild：需求是授权、角色、发放奖励、通知奖励。一个任务10u，pr合并进去就会被webhook通知记录。项目owner reward USDT 10、trans USDT 10、revoke。不同的PR不同的价值，需要手动设定奖励数值。

微扰：不清楚外面的资金存储、发放、接受度的问题。

openbuild：希望Bounty和github能紧密结合。往后推进就是bootcamp、黑客松这些。目前网站上的bounty没什么结合点。有贡献度查看。一个场景，openbuild之前拿1000u给某个项目，开发者提交时间、owner可以决定价值。web3很多项目都是有贡献奖励的，60~70%。对他们来说统计这些贡献很麻烦。

![original_1724747306578_7dbf201bd31c6a455389fc216e30135e](https://github.com/user-attachments/assets/85d9578b-7f04-47c1-aea2-55ccf0668cc7)

git.ts

openbuild：github的贡献价值其实很难评估，很多项目都是在手动调节。他们需要统计这些贡献，不一定发奖励。PR、ISSUE愿意在github评论的在里面以特定格式评论，自动化处理，不愿意的在系统里展示里管理。

**Comment by Fajar778-ops** [comment]
start
