### ISSUE TITLE
[UI Enhancement] Task card ui enhancement

### ISSUE THREAD

**Issue by Amateur0x1** [YoubetDao/youbet-task#73]
The previous UI hasn't looked good because I wanted to display GitHub's tag information here, but I think it's better to stop displaying the tags due to the limited space. Therefore, I've decided to remove them. Additionally, I will render the Markdown plain text to HTML using markdown-it, and then extract the plain text by stripping out the tags.

**Comment by wfnuser** [comment]
Good Jobs. Closed by #74
