### ISSUE TITLE
dapps error

### ISSUE THREAD

**Issue by elgirz** [YoubetDao/youbet-task#76]
dapss error

**Comment by wfnuser** [comment]
Hi. @elgirz  Can you provide more details?

**Comment by wfnuser** [comment]
I would like to claim this issue.

**Comment by wfnuser** [comment]
I would like to claim this issue.

**Comment by wfnuser** [comment]
I would like to claim this issue.

**Comment by wfnuser** [comment]
I would like to claim this issue.

**Comment by wfnuser** [comment]
I would like to claim this issue.

**Comment by wfnuser** [comment]
I would like to claim this issue.
