### ISSUE TITLE
[UI Enhancement] 导入项目时选择组织后需要加载一段时间 - 请增加 loading effect 效果

### ISSUE THREAD

**Issue by wfnuser** [YoubetDao/youbet-task#93]
![image](https://github.com/user-attachments/assets/bbf57723-0cf0-4f49-97e8-ab66e46a5213)
请增加 loading effect 效果 - 让用户意识到目前正在加载 repo 列表

**Comment by Vinnyaaaaa** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by curie123** [comment]
I would like to claim this issue.

**Comment by curie123** [comment]
How do I get involved?

**Comment by wfnuser** [comment]
> How do I get involved?

Hi, @curie123. Some one has already taken it. If you're interested maybe you can add my wechat, I will create more tickets recently.
